package My;


	import java.util.ArrayList;
	import javax.swing.JButton;
	package My;

	/*
	 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
	 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
	 */

	/
	 *
	 * @author manel
	 */

	public class PopUp extends javax.swing.JFrame {

	   String cardImage="";
	   Game game;
	   ArrayList<UnoCard> playerHand;
	   int choice ;
	   ArrayList<JButton> cardButtons;
	   UnoCard.Color declaredColor;
	    public PopUp(String cardname,Game game , int index , ArrayList<JButton>cardbutton, gameStage gamestage ,JButton topCardButton) {
	        initComponents();
	        cardImage=cardname;
	        this.game=game;
	        playerHand=game.getPlayerHand(game.getCurrentPlayer());
	        choice=index;
	        CardLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Uno Game  Assets"+cardImage+".png")));
	        this.gamestage=gamestage;
	        this.topCardButtom=topCardButtom;
	    }
	    public PopUp(){};
	    /
	     * This method is called from within the constructor to initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is always
	     * regenerated by the Form Editor.
	     */
	    @SuppressWarnings("unchecked")
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	    private void initComponents() {

	        jPanel1 = new javax.swing.JPanel();
	        usebutton = new javax.swing.JButton();
	        cancelbutton = new javax.swing.JButton();

	        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

	        jPanel1.setBackground(new java.awt.Color(255, 204, 0));

	        usebutton.setBackground(new java.awt.Color(153, 0, 0));
	        usebutton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
	        usebutton.setText("use card");
	        usebutton.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                usebuttonActionPerformed(evt);
	            }
	        });

	        cancelbutton.setBackground(new java.awt.Color(153, 0, 0));
	        cancelbutton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
	        cancelbutton.setText("cancel");
	        cancelbutton.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                cancelbuttonActionPerformed(evt);
	            }
	        });

	        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
	        jPanel1.setLayout(jPanel1Layout);
	        jPanel1Layout.setHorizontalGroup(
	            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(jPanel1Layout.createSequentialGroup()
	                .addGap(55, 55, 55)
	                .addComponent(usebutton)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 243, Short.MAX_VALUE)
	                .addComponent(cancelbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addGap(73, 73, 73))
	        );
	        jPanel1Layout.setVerticalGroup(
	            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
	                .addContainerGap(423, Short.MAX_VALUE)
	                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
	                    .addComponent(usebutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                    .addComponent(cancelbutton, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE))
	                .addGap(66, 66, 66))
	        );
}
